[build]
builder = "NIXPACKS"

[build.nixpacks]
nixPkgs = ["nodejs_22"]
installCmd = "echo 'Skipping install — prebuilt'"
buildCmd = "echo 'Skipping build — prebuilt'"

[start]
cmd = "node server.mjs"
