"use client";

import { useState } from "react";
import type { Translations } from "@/lib/i18n";

interface FeaturesSectionProps {
  t: Translations;
}

/* ── Feature data ─────────────────────────────────────────────────────────── */

const FEATURES = [
  {
    id: "ai-chat",
    label: "AI Chat Editor",
    title: "Describe changes. The AI writes the code.",
    description:
      "No drag-and-drop, no menus to learn. Just type what you want in plain language — \"make the hero darker and add a booking button\" — and the AI edits your real React code instantly. It understands context across your entire site.",
    detail: "Every instruction updates your live codebase. You see a real diff, approve it, and it ships.",
    color: "#22d3ee",
    side: "left",
    codeSnippet: {
      label: "Your message",
      lines: [
        { text: '> "Add a testimonials section with 3 reviews"', type: "input" },
        { text: "AI is writing TestimonialsSection.tsx...", type: "meta" },
        { text: "+ export function TestimonialsSection() {", type: "add" },
        { text: '+   return <section className="py-24">...', type: "add" },
        { text: "3 files changed, 87 insertions", type: "meta" },
      ],
    },
    icon: (
      <svg viewBox="0 0 48 48" fill="none" className="w-10 h-10" aria-hidden>
        <circle cx="24" cy="24" r="22" fill="currentColor" fillOpacity="0.08" />
        <path d="M16 17h16M16 23h10M16 29h8" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
        <circle cx="34" cy="30" r="6" fill="currentColor" fillOpacity="0.15" stroke="currentColor" strokeWidth="1.5" />
        <path d="M32 30l1.5 1.5L35.5 28" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
      </svg>
    ),
  },
  {
    id: "real-code",
    label: "Real Code",
    title: "Real React. Not blocks, not themes.",
    description:
      "Every site MadeCreative builds is production-quality React + Next.js + Tailwind CSS. You own the code. You can export it, hand it to a developer, or self-host — no lock-in. The output is the same code a senior frontend engineer would write.",
    detail: "TypeScript, App Router, SSR, image optimization — everything is included by default.",
    color: "#6366f1",
    side: "right",
    codeSnippet: {
      label: "Generated code",
      lines: [
        { text: "// app/page.tsx — generated by MadeCreative AI", type: "meta" },
        { text: 'import { HeroSection } from "@/components"', type: "normal" },
        { text: 'import { BookingModal } from "@/components"', type: "normal" },
        { text: "", type: "normal" },
        { text: "export default function Page() {", type: "normal" },
        { text: '  return <main className="bg-stone-950">', type: "normal" },
        { text: "    <HeroSection />", type: "add" },
        { text: "    <BookingModal />", type: "add" },
      ],
    },
    icon: (
      <svg viewBox="0 0 48 48" fill="none" className="w-10 h-10" aria-hidden>
        <circle cx="24" cy="24" r="22" fill="currentColor" fillOpacity="0.08" />
        <path d="M18 17l-6 7 6 7M30 17l6 7-6 7" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
        <path d="M26 14l-4 20" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" />
      </svg>
    ),
  },
  {
    id: "live-preview",
    label: "Live Preview",
    title: "Watch your site build itself in real-time.",
    description:
      "As the AI writes code, your preview updates live. You see every change — layout, colors, components — the instant they are generated. It feels like pair-programming with the fastest developer you have ever worked with.",
    detail: "Split-panel view: chat on the left, live site on the right. No refresh needed.",
    color: "#34d399",
    side: "left",
    codeSnippet: {
      label: "Live stream",
      lines: [
        { text: "BUILDER  writing HeroSection.tsx", type: "meta" },
        { text: "BUILDER  writing NavBar.tsx", type: "meta" },
        { text: "BUILDER  updating globals.css", type: "meta" },
        { text: "PREVIEW  hot-reload triggered", type: "add" },
        { text: "PREVIEW  rendered in 180ms", type: "add" },
        { text: "QA       accessibility pass ✓", type: "add" },
      ],
    },
    icon: (
      <svg viewBox="0 0 48 48" fill="none" className="w-10 h-10" aria-hidden>
        <circle cx="24" cy="24" r="22" fill="currentColor" fillOpacity="0.08" />
        <rect x="11" y="14" width="26" height="16" rx="2" stroke="currentColor" strokeWidth="2" />
        <path d="M17 30v4M31 30v4M15 34h18" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" />
        <circle cx="24" cy="22" r="3" fill="currentColor" fillOpacity="0.3" stroke="currentColor" strokeWidth="1.5" />
        <path d="M24 20v4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
      </svg>
    ),
  },
  {
    id: "any-site",
    label: "Any Type of Site",
    title: "Landing page, e-commerce, SaaS — anything.",
    description:
      "The AI is not limited to templates. Describe what you need and it builds from scratch. Restaurant booking flows, e-commerce product pages, SaaS dashboards, portfolio galleries, appointment funnels — all generated to your exact specification.",
    detail: "If you can describe it, MadeCreative can build it. Multi-page, multi-language, multi-currency.",
    color: "#f472b6",
    side: "right",
    codeSnippet: null,
    useCaseGrid: [
      "Restaurant", "Dental clinic", "E-commerce", "Portfolio",
      "SaaS landing", "Real estate", "Fitness studio", "Law firm",
    ],
    icon: (
      <svg viewBox="0 0 48 48" fill="none" className="w-10 h-10" aria-hidden>
        <circle cx="24" cy="24" r="22" fill="currentColor" fillOpacity="0.08" />
        <rect x="10" y="12" width="12" height="10" rx="1.5" stroke="currentColor" strokeWidth="1.75" />
        <rect x="26" y="12" width="12" height="10" rx="1.5" stroke="currentColor" strokeWidth="1.75" />
        <rect x="10" y="26" width="12" height="10" rx="1.5" stroke="currentColor" strokeWidth="1.75" />
        <rect x="26" y="26" width="12" height="10" rx="1.5" stroke="currentColor" strokeWidth="1.75" />
      </svg>
    ),
  },
  {
    id: "seo",
    label: "Built-in SEO",
    title: "SEO that works out of the box — automatically.",
    description:
      "Schema.org structured data, Open Graph meta tags, Twitter cards, auto-generated XML sitemaps, canonical URLs, and performance-first rendering. Every site scores 95+ on Google PageSpeed by default — no plugins required.",
    detail: "Built for local SEO too: business address, opening hours, review schema — all wired up.",
    color: "#fbbf24",
    side: "left",
    codeSnippet: {
      label: "Auto-generated meta",
      lines: [
        { text: "<head>", type: "normal" },
        { text: '  <title>Ristorante da Marco — Milano</title>', type: "add" },
        { text: '  <meta name="description" content="..." />', type: "add" },
        { text: '  <meta property="og:image" content="..." />', type: "add" },
        { text: '  <script type="application/ld+json">', type: "add" },
        { text: '    { "@type": "Restaurant", ... }', type: "add" },
        { text: "  </script>", type: "normal" },
      ],
    },
    icon: (
      <svg viewBox="0 0 48 48" fill="none" className="w-10 h-10" aria-hidden>
        <circle cx="24" cy="24" r="22" fill="currentColor" fillOpacity="0.08" />
        <circle cx="22" cy="22" r="8" stroke="currentColor" strokeWidth="2" />
        <path d="M28 28l5.5 5.5" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
        <path d="M19 22h6M22 19v6" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
      </svg>
    ),
  },
  {
    id: "deploy",
    label: "Instant Deploy",
    title: "From chat to live URL in under 60 seconds.",
    description:
      "One click deploys your site to a global CDN with automatic SSL, custom domain support, and zero configuration. No Vercel account, no GitHub, no CI/CD pipelines to set up. MadeCreative handles the entire infrastructure.",
    detail: "Automatic preview URLs for every change, plus instant rollback to any previous version.",
    color: "#818cf8",
    side: "right",
    codeSnippet: {
      label: "Deploy log",
      lines: [
        { text: "Building for production...", type: "meta" },
        { text: "Optimizing images (23 assets)...", type: "meta" },
        { text: "Generating static pages (8/8)...", type: "meta" },
        { text: "Deploying to edge network...", type: "meta" },
        { text: "SSL certificate issued.", type: "add" },
        { text: "Live: https://darco-milano.madecreative.pro", type: "add" },
      ],
    },
    icon: (
      <svg viewBox="0 0 48 48" fill="none" className="w-10 h-10" aria-hidden>
        <circle cx="24" cy="24" r="22" fill="currentColor" fillOpacity="0.08" />
        <path d="M24 34V22" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
        <path d="M24 22l-5 5M24 22l5 5" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
        <path d="M14 30c-2.5-1-4-3.5-4-6a8 8 0 0116 0" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" />
        <path d="M34 30c2.5-1 4-3.5 4-6" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" />
      </svg>
    ),
  },
  {
    id: "version-history",
    label: "Version History",
    title: "Every edit is saved. Undo anything instantly.",
    description:
      "Every change you make through the AI chat creates an automatic snapshot. Accidentally broke something? Roll back to any previous state with one click. No technical knowledge needed — it works like an infinite undo button for your entire site.",
    detail: "Snapshots are named by the AI so you can find them fast: \"Added booking modal\" or \"Changed hero colors\".",
    color: "#a78bfa",
    side: "left",
    codeSnippet: {
      label: "Version history",
      lines: [
        { text: "v14  Added booking modal         2m ago", type: "add" },
        { text: "v13  Changed hero background      1h ago", type: "normal" },
        { text: "v12  Updated menu prices          3h ago", type: "normal" },
        { text: "v11  Added testimonials section  Yesterday", type: "normal" },
        { text: "v10  Fixed mobile layout         2 days ago", type: "normal" },
      ],
    },
    icon: (
      <svg viewBox="0 0 48 48" fill="none" className="w-10 h-10" aria-hidden>
        <circle cx="24" cy="24" r="22" fill="currentColor" fillOpacity="0.08" />
        <path d="M13 24a11 11 0 1011-11" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
        <path d="M13 24l-3-4M13 24l4-3" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
        <path d="M24 18v7l4 3" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round" />
      </svg>
    ),
  },
  {
    id: "mobile-first",
    label: "Mobile-First",
    title: "Looks perfect on every screen, automatically.",
    description:
      "The AI generates fully responsive layouts by default. Every component is designed mobile-first with Tailwind's responsive utilities. Your site is tested at 320px, 768px, and 1440px before it ever goes live — no extra configuration.",
    detail: "Touch-friendly navigation, optimal font sizes, and fast loading on mobile networks — built in.",
    color: "#fb923c",
    side: "right",
    codeSnippet: null,
    devicePreview: true,
    icon: (
      <svg viewBox="0 0 48 48" fill="none" className="w-10 h-10" aria-hidden>
        <circle cx="24" cy="24" r="22" fill="currentColor" fillOpacity="0.08" />
        <rect x="18" y="11" width="12" height="20" rx="2" stroke="currentColor" strokeWidth="1.75" />
        <circle cx="24" cy="28" r="1" fill="currentColor" />
        <rect x="10" y="16" width="8" height="14" rx="1.5" stroke="currentColor" strokeWidth="1.5" strokeOpacity="0.4" />
        <rect x="30" y="16" width="8" height="14" rx="1.5" stroke="currentColor" strokeWidth="1.5" strokeOpacity="0.4" />
      </svg>
    ),
  },
] as const;

/* ── Code block sub-component ─────────────────────────────────────────────── */

function CodeBlock({
  snippet,
  color,
}: {
  snippet: NonNullable<(typeof FEATURES)[number]["codeSnippet"]>;
  color: string;
}) {
  return (
    <div
      className="rounded-xl overflow-hidden font-mono text-xs"
      style={{
        background: "#080c14",
        border: "1px solid rgba(255,255,255,0.07)",
      }}
    >
      <div
        className="flex items-center gap-2 px-4 py-2.5"
        style={{ borderBottom: "1px solid rgba(255,255,255,0.05)" }}
      >
        <div className="w-2.5 h-2.5 rounded-full bg-red-500/50" />
        <div className="w-2.5 h-2.5 rounded-full bg-yellow-500/50" />
        <div className="w-2.5 h-2.5 rounded-full bg-green-500/50" />
        <span className="ml-2 text-[10px]" style={{ color: "rgba(248,250,252,0.25)" }}>
          {snippet.label}
        </span>
      </div>
      <div className="p-4 space-y-1.5">
        {snippet.lines.map((line, i) => (
          <div
            key={i}
            className="flex gap-3"
            style={{
              color:
                line.type === "add"
                  ? color
                  : line.type === "meta"
                  ? "rgba(248,250,252,0.3)"
                  : "rgba(248,250,252,0.55)",
            }}
          >
            {line.type === "add" && (
              <span style={{ color, opacity: 0.7, flexShrink: 0 }}>+</span>
            )}
            {line.type !== "add" && (
              <span style={{ color: "rgba(248,250,252,0.12)", flexShrink: 0 }}>
                {String(i + 1).padStart(2, " ")}
              </span>
            )}
            <span>{line.text}</span>
          </div>
        ))}
      </div>
    </div>
  );
}

/* ── Use-case pill grid ───────────────────────────────────────────────────── */

function UseCasePills({ items, color }: { items: readonly string[]; color: string }) {
  return (
    <div className="flex flex-wrap gap-2">
      {items.map((item) => (
        <span
          key={item}
          className="px-3 py-1.5 rounded-full text-xs font-medium"
          style={{
            background: `${color}12`,
            border: `1px solid ${color}30`,
            color,
          }}
        >
          {item}
        </span>
      ))}
    </div>
  );
}

/* ── Device preview mock ──────────────────────────────────────────────────── */

function DevicePreview({ color }: { color: string }) {
  return (
    <div className="flex items-end gap-4 justify-center py-4">
      {/* Desktop */}
      <div
        className="rounded-lg overflow-hidden"
        style={{ border: "1px solid rgba(255,255,255,0.1)", width: 160 }}
      >
        <div
          className="h-4 flex items-center gap-1.5 px-2"
          style={{ background: "#0d1117", borderBottom: "1px solid rgba(255,255,255,0.06)" }}
        >
          {[0, 1, 2].map((d) => (
            <div key={d} className="w-1.5 h-1.5 rounded-full" style={{ background: "rgba(255,255,255,0.12)" }} />
          ))}
        </div>
        <div style={{ background: "#161b27", padding: 8 }}>
          <div className="h-2 rounded mb-1.5" style={{ background: color, opacity: 0.3, width: "70%" }} />
          <div className="h-1.5 rounded mb-1" style={{ background: "rgba(255,255,255,0.08)", width: "90%" }} />
          <div className="h-1.5 rounded mb-1" style={{ background: "rgba(255,255,255,0.08)", width: "75%" }} />
          <div className="h-1.5 rounded mb-2" style={{ background: "rgba(255,255,255,0.08)", width: "60%" }} />
          <div className="h-5 rounded" style={{ background: color, opacity: 0.4, width: 48 }} />
        </div>
      </div>

      {/* Tablet */}
      <div
        className="rounded-lg overflow-hidden"
        style={{ border: "1px solid rgba(255,255,255,0.1)", width: 100 }}
      >
        <div style={{ background: "#161b27", padding: 6 }}>
          <div className="h-1.5 rounded mb-1" style={{ background: color, opacity: 0.3, width: "80%" }} />
          <div className="h-1 rounded mb-1" style={{ background: "rgba(255,255,255,0.08)", width: "100%" }} />
          <div className="h-1 rounded mb-2" style={{ background: "rgba(255,255,255,0.08)", width: "90%" }} />
          <div className="h-4 rounded" style={{ background: color, opacity: 0.4, width: 40 }} />
        </div>
        <div
          className="h-2 flex justify-center items-center"
          style={{ background: "#0d1117", borderTop: "1px solid rgba(255,255,255,0.06)" }}
        >
          <div className="w-3 h-1 rounded-full" style={{ background: "rgba(255,255,255,0.15)" }} />
        </div>
      </div>

      {/* Mobile */}
      <div
        className="rounded-xl overflow-hidden"
        style={{ border: "1px solid rgba(255,255,255,0.1)", width: 60 }}
      >
        <div
          className="h-2 flex justify-center items-center"
          style={{ background: "#0d1117", borderBottom: "1px solid rgba(255,255,255,0.06)" }}
        >
          <div className="w-4 h-0.5 rounded-full" style={{ background: "rgba(255,255,255,0.15)" }} />
        </div>
        <div style={{ background: "#161b27", padding: 5 }}>
          <div className="h-1.5 rounded mb-1" style={{ background: color, opacity: 0.35, width: "100%" }} />
          <div className="h-1 rounded mb-0.5" style={{ background: "rgba(255,255,255,0.08)", width: "100%" }} />
          <div className="h-1 rounded mb-2" style={{ background: "rgba(255,255,255,0.08)", width: "80%" }} />
          <div className="h-3 rounded" style={{ background: color, opacity: 0.45, width: "100%" }} />
        </div>
        <div
          className="h-2 flex justify-center items-center"
          style={{ background: "#0d1117", borderTop: "1px solid rgba(255,255,255,0.06)" }}
        >
          <div className="w-3 h-3 rounded-full" style={{ border: "1px solid rgba(255,255,255,0.15)" }} />
        </div>
      </div>
    </div>
  );
}

/* ── Feature row ──────────────────────────────────────────────────────────── */

type Feature = (typeof FEATURES)[number];

function FeatureRow({ feature, index }: { feature: Feature; index: number }) {
  const [hovered, setHovered] = useState(false);
  const isRight = feature.side === "right";

  const textBlock = (
    <div className="flex flex-col justify-center">
      <div className="flex items-center gap-3 mb-5">
        <div
          className="w-14 h-14 rounded-2xl flex items-center justify-center flex-shrink-0 transition-all duration-300"
          style={{
            background: hovered ? `${feature.color}18` : `${feature.color}0d`,
            border: `1px solid ${feature.color}${hovered ? "40" : "20"}`,
            color: feature.color,
            boxShadow: hovered ? `0 0 32px ${feature.color}25` : "none",
          }}
        >
          {feature.icon}
        </div>
        <span
          className="text-xs font-bold uppercase tracking-widest"
          style={{ color: feature.color }}
        >
          {feature.label}
        </span>
      </div>

      <h3
        className="text-2xl sm:text-3xl font-bold leading-snug mb-4"
        style={{ color: "#f8fafc" }}
      >
        {feature.title}
      </h3>

      <p className="text-base leading-relaxed mb-3" style={{ color: "rgba(248,250,252,0.55)" }}>
        {feature.description}
      </p>

      <p className="text-sm leading-relaxed" style={{ color: "rgba(248,250,252,0.35)" }}>
        {feature.detail}
      </p>

      <div
        className="mt-6 h-px w-16 rounded-full"
        style={{ background: feature.color, opacity: hovered ? 0.6 : 0.2 }}
      />
    </div>
  );

  const visualBlock = (
    <div className="flex flex-col justify-center">
      {"codeSnippet" in feature && feature.codeSnippet ? (
        <CodeBlock snippet={feature.codeSnippet} color={feature.color} />
      ) : "useCaseGrid" in feature && feature.useCaseGrid ? (
        <div
          className="rounded-xl p-6"
          style={{
            background: "#0d1117",
            border: "1px solid rgba(255,255,255,0.07)",
          }}
        >
          <p
            className="text-xs font-semibold uppercase tracking-widest mb-4"
            style={{ color: "rgba(248,250,252,0.25)" }}
          >
            Works for any industry
          </p>
          <UseCasePills items={feature.useCaseGrid} color={feature.color} />
        </div>
      ) : "devicePreview" in feature && feature.devicePreview ? (
        <div
          className="rounded-xl p-6"
          style={{
            background: "#0d1117",
            border: "1px solid rgba(255,255,255,0.07)",
          }}
        >
          <p
            className="text-xs font-semibold uppercase tracking-widest mb-2 text-center"
            style={{ color: "rgba(248,250,252,0.25)" }}
          >
            Responsive on every device
          </p>
          <DevicePreview color={feature.color} />
        </div>
      ) : null}
    </div>
  );

  return (
    <div
      className="group relative rounded-3xl p-8 sm:p-10 lg:p-12 transition-all duration-500"
      style={{
        background: hovered
          ? "rgba(255,255,255,0.025)"
          : "rgba(255,255,255,0.015)",
        border: hovered
          ? `1px solid ${feature.color}20`
          : "1px solid rgba(255,255,255,0.06)",
      }}
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
    >
      {/* Step number watermark */}
      <div
        className="absolute top-6 right-8 text-6xl font-black select-none pointer-events-none"
        style={{ color: "rgba(255,255,255,0.025)", fontVariantNumeric: "tabular-nums" }}
        aria-hidden
      >
        0{index + 1}
      </div>

      <div
        className={`grid grid-cols-1 lg:grid-cols-2 gap-10 lg:gap-16 items-center ${
          isRight ? "lg:[direction:rtl]" : ""
        }`}
      >
        <div className={isRight ? "[direction:ltr]" : ""}>{textBlock}</div>
        <div className={isRight ? "[direction:ltr]" : ""}>{visualBlock}</div>
      </div>
    </div>
  );
}

/* ── Section ──────────────────────────────────────────────────────────────── */

export function FeaturesSection({ t }: FeaturesSectionProps) {
  return (
    <section
      id="features"
      className="py-32 px-4 sm:px-6 lg:px-8"
      style={{ background: "#05070f" }}
    >
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="text-center mb-20">
          <span
            className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full text-xs font-medium mb-6"
            style={{
              background: "rgba(99,102,241,0.1)",
              border: "1px solid rgba(99,102,241,0.2)",
              color: "#818cf8",
            }}
          >
            {t.features.sectionLabel}
          </span>

          <h2
            className="text-3xl sm:text-4xl md:text-5xl lg:text-6xl font-bold leading-tight mb-6"
            style={{ color: "#f8fafc" }}
          >
            Everything you need.
            <br />
            <span style={{ color: "#6366f1" }}>Nothing you don&apos;t.</span>
          </h2>

          <p
            className="text-lg sm:text-xl max-w-2xl mx-auto leading-relaxed"
            style={{ color: "rgba(248,250,252,0.5)" }}
          >
            MadeCreative is a complete platform — from AI-powered code generation to global
            deployment. No stitching together tools. No configuration rabbit holes.
          </p>
        </div>

        {/* Feature rows */}
        <div className="space-y-6">
          {FEATURES.map((feature, i) => (
            <FeatureRow key={feature.id} feature={feature} index={i} />
          ))}
        </div>
      </div>
    </section>
  );
}
