import { z } from "zod";

// ─── Design Specification ─────────────────────────────────────────────────────
// Single source of truth shared across Landing Page, Portal, and Campaign.
// Generated by the design agent pipeline (Research → Stitch → UI Components).
// ─────────────────────────────────────────────────────────────────────────────

// ─── Brand Assets ─────────────────────────────────────────────────────────────

export const BrandAssetSchema = z.object({
  url: z.string().url(),
  source: z.enum([
    "original_site", "google_maps", "facebook", "instagram",
    "tripadvisor", "pexels", "unsplash", "stitch_generated",
  ]),
  type: z.enum(["logo", "hero", "gallery", "team", "product", "interior", "exterior", "food", "other"]),
  width: z.number().int().optional(),
  height: z.number().int().optional(),
  qualityScore: z.number().min(0).max(10).optional(),
  alt: z.string().optional(),
});

export type BrandAsset = z.infer<typeof BrandAssetSchema>;

// ─── Color System ─────────────────────────────────────────────────────────────

export const ColorSystemSchema = z.object({
  primary: z.string().describe("Dominant dark/rich color from brand"),
  secondary: z.string().describe("Supporting color for secondary elements"),
  accent: z.string().describe("Most vibrant/characteristic brand color"),
  background: z.string().describe("Light background (never pure white)"),
  surface: z.string().describe("Card/elevated surface color"),
  text: z.string().describe("Primary text color (dark but not pure black)"),
  textMuted: z.string().describe("Secondary/muted text color"),
  border: z.string().describe("Subtle border color"),
  success: z.string().default("#22c55e"),
  error: z.string().default("#ef4444"),
  /** Raw values extracted from the original site or photos */
  extractedFrom: z.enum(["original_site", "photos", "stitch", "sector_default"]).optional(),
});

export type ColorSystem = z.infer<typeof ColorSystemSchema>;

// ─── Typography System ────────────────────────────────────────────────────────

export const TypographySystemSchema = z.object({
  headingFont: z.string().describe("Premium heading font family"),
  bodyFont: z.string().describe("Clean body font family"),
  monoFont: z.string().default("JetBrains Mono").describe("Monospace font"),
  googleFontsUrl: z.string().url().describe("Google Fonts CSS import URL"),
  /** Scale: clamp values for responsive typography */
  scale: z.object({
    hero: z.string().default("clamp(3rem, 7vw, 6rem)"),
    h1: z.string().default("clamp(2.5rem, 5vw, 4.5rem)"),
    h2: z.string().default("clamp(1.8rem, 3.5vw, 3rem)"),
    h3: z.string().default("clamp(1.3rem, 2.5vw, 2rem)"),
    h4: z.string().default("clamp(1.1rem, 2vw, 1.5rem)"),
    body: z.string().default("1rem"),
    small: z.string().default("0.875rem"),
    xs: z.string().default("0.75rem"),
  }).default({}),
  headingWeight: z.number().default(400),
  bodyWeight: z.number().default(400),
  lineHeight: z.object({
    heading: z.number().default(1.1),
    body: z.number().default(1.75),
  }).default({}),
  letterSpacing: z.object({
    heading: z.string().default("-0.02em"),
    label: z.string().default("0.2em"),
    body: z.string().default("0em"),
  }).default({}),
});

export type TypographySystem = z.infer<typeof TypographySystemSchema>;

// ─── Spacing & Layout ─────────────────────────────────────────────────────────

export const LayoutSystemSchema = z.object({
  maxWidth: z.string().default("1280px"),
  sectionPadding: z.string().default("clamp(4rem, 8vw, 8rem)"),
  containerPadding: z.string().default("clamp(1rem, 3vw, 2.5rem)"),
  gap: z.object({
    xs: z.string().default("0.5rem"),
    sm: z.string().default("1rem"),
    md: z.string().default("1.5rem"),
    lg: z.string().default("2.5rem"),
    xl: z.string().default("4rem"),
    xxl: z.string().default("6rem"),
  }).default({}),
  borderRadius: z.object({
    sm: z.string().default("4px"),
    md: z.string().default("8px"),
    lg: z.string().default("16px"),
    full: z.string().default("9999px"),
  }).default({}),
  gridColumns: z.number().default(12),
});

export type LayoutSystem = z.infer<typeof LayoutSystemSchema>;

// ─── Animation System ─────────────────────────────────────────────────────────

export const AnimationPresetSchema = z.object({
  name: z.string(),
  type: z.enum([
    "scroll_reveal", "hero_entrance", "hover_effect",
    "page_transition", "loading", "parallax",
    "text_reveal", "stagger", "magnetic", "morph",
    "spotlight", "aurora", "particles", "gradient_shift",
    "blur_reveal", "counter", "typewriter",
  ]),
  config: z.record(z.unknown()).describe("Framer Motion / CSS config"),
  /** Which component types this animation applies to */
  appliesTo: z.array(z.string()).optional(),
});

export type AnimationPreset = z.infer<typeof AnimationPresetSchema>;

export const AnimationSystemSchema = z.object({
  /** Global entrance animation for sections */
  scrollReveal: AnimationPresetSchema.default({
    name: "fade_up",
    type: "scroll_reveal",
    config: {
      initial: { opacity: 0, y: 40 },
      animate: { opacity: 1, y: 0 },
      transition: { duration: 0.7, ease: [0.25, 0.46, 0.45, 0.94] },
    },
  }),
  /** Hero text entrance */
  heroEntrance: AnimationPresetSchema.default({
    name: "character_reveal",
    type: "hero_entrance",
    config: {
      stagger: 0.03,
      duration: 0.6,
      ease: [0.25, 0.46, 0.45, 0.94],
    },
  }),
  /** Nav scroll behavior */
  navTransition: z.object({
    transparent: z.boolean().default(true),
    blurOnScroll: z.boolean().default(true),
    scrollThreshold: z.number().default(60),
  }).default({}),
  /** Premium effects (Aceternity/Magic UI inspired) */
  premiumEffects: z.array(AnimationPresetSchema).default([]),
  /** Page transition */
  pageTransition: AnimationPresetSchema.default({
    name: "fade_in",
    type: "page_transition",
    config: {
      initial: { opacity: 0 },
      animate: { opacity: 1 },
      transition: { duration: 0.4 },
    },
  }),
});

export type AnimationSystem = z.infer<typeof AnimationSystemSchema>;

// ─── Component Variant Registry ───────────────────────────────────────────────

export const ComponentVariantSchema = z.object({
  component: z.string().describe("Component name: hero, gallery, testimonials, etc."),
  variant: z.string().describe("Variant name: split_parallax, masonry, carousel, etc."),
  premiumLevel: z.enum(["standard", "premium", "ultra"]).default("premium"),
  /** Animation effects attached to this component */
  effects: z.array(z.string()).default([]),
  /** Aceternity/Magic UI component reference */
  uiLibrary: z.enum(["aceternity", "magic_ui", "custom", "stitch"]).optional(),
  uiComponent: z.string().optional().describe("Specific library component name"),
  config: z.record(z.unknown()).default({}),
});

export type ComponentVariant = z.infer<typeof ComponentVariantSchema>;

// ─── Section Definition ───────────────────────────────────────────────────────

export const SectionDefinitionSchema = z.object({
  id: z.string(),
  type: z.enum([
    "hero", "about", "services", "gallery", "testimonials",
    "team", "contact", "pricing", "faq", "cta", "stats",
    "features", "process", "portfolio", "menu", "rooms",
    "listings", "newsletter", "footer",
  ]),
  order: z.number().int(),
  variant: ComponentVariantSchema,
  content: z.record(z.unknown()).default({}),
  visible: z.boolean().default(true),
});

export type SectionDefinition = z.infer<typeof SectionDefinitionSchema>;

// ─── Stitch Integration ───────────────────────────────────────────────────────

export const StitchScreenSchema = z.object({
  screenId: z.string(),
  projectId: z.string(),
  name: z.string(),
  htmlUrl: z.string().url().optional(),
  imageUrl: z.string().url().optional(),
  deviceType: z.enum(["DESKTOP", "MOBILE", "TABLET", "AGNOSTIC"]).default("DESKTOP"),
});

export type StitchScreen = z.infer<typeof StitchScreenSchema>;

export const StitchDesignSystemSchema = z.object({
  projectId: z.string(),
  designSystemId: z.string().optional(),
  screens: z.array(StitchScreenSchema).default([]),
  exportedHtml: z.record(z.string()).default({}),
  exportedReact: z.record(z.string()).default({}),
});

export type StitchDesignSystem = z.infer<typeof StitchDesignSystemSchema>;

// ─── Scraped Original Content ─────────────────────────────────────────────────

export const ScrapedContentSchema = z.object({
  /** Original site URL */
  sourceUrl: z.string().url().optional(),
  /** Logo extracted from the original site */
  logo: BrandAssetSchema.optional(),
  /** All photos found on the original site */
  photos: z.array(BrandAssetSchema).default([]),
  /** Business name as displayed on the site */
  businessName: z.string().optional(),
  /** Tagline/slogan from the site */
  tagline: z.string().optional(),
  /** Main headings from the site */
  headings: z.array(z.string()).default([]),
  /** Body text/descriptions */
  bodyTexts: z.array(z.string()).default([]),
  /** Colors extracted from the original site CSS */
  extractedColors: z.array(z.string()).default([]),
  /** Fonts detected on the original site */
  detectedFonts: z.array(z.string()).default([]),
  /** Phone numbers found */
  phones: z.array(z.string()).default([]),
  /** Emails found */
  emails: z.array(z.string()).default([]),
  /** Address found */
  address: z.string().optional(),
  /** Social media links */
  socialLinks: z.record(z.string()).default({}),
  /** Business hours */
  businessHours: z.record(z.string()).default({}),
  /** Menu items (for restaurants) */
  menuItems: z.array(z.object({
    name: z.string(),
    description: z.string().optional(),
    price: z.string().optional(),
    category: z.string().optional(),
  })).default([]),
  /** Services offered */
  services: z.array(z.object({
    name: z.string(),
    description: z.string().optional(),
    price: z.string().optional(),
  })).default([]),
  /** Reviews/testimonials from the site */
  testimonials: z.array(z.object({
    text: z.string(),
    author: z.string().optional(),
    rating: z.number().optional(),
  })).default([]),
});

export type ScrapedContent = z.infer<typeof ScrapedContentSchema>;

// ─── DESIGN SPEC: The Master Document ─────────────────────────────────────────
// This is the single source of truth that drives all three outputs:
// Landing Page (preview), Portal (editor), and Campaign (email).

export const DesignSpecSchema = z.object({
  /** Unique spec ID */
  id: z.string(),
  /** Version for tracking iterations */
  version: z.number().int().default(1),
  /** Creation timestamp */
  createdAt: z.string().datetime(),
  /** Last updated */
  updatedAt: z.string().datetime(),

  /** Business identity */
  business: z.object({
    name: z.string(),
    sector: z.string(),
    country: z.string(),
    language: z.string(),
    city: z.string().optional(),
    description: z.string().optional(),
    googleRating: z.number().optional(),
    reviewCount: z.number().optional(),
  }),

  /** Original content scraped from the business site */
  scrapedContent: ScrapedContentSchema.optional(),

  /** Design systems */
  colors: ColorSystemSchema,
  typography: TypographySystemSchema,
  layout: LayoutSystemSchema,
  animations: AnimationSystemSchema,

  /** Brand assets (logo + curated photos) */
  assets: z.object({
    logo: BrandAssetSchema.optional(),
    heroImage: BrandAssetSchema.optional(),
    photos: z.array(BrandAssetSchema).default([]),
    /** Photo source breakdown */
    photoSources: z.object({
      original: z.number().default(0),
      stock: z.number().default(0),
      stitchGenerated: z.number().default(0),
    }).default({}),
  }),

  /** Generated copy */
  content: z.object({
    tagline: z.string(),
    heroTitle: z.string(),
    heroSubtitle: z.string(),
    aboutTitle: z.string().optional(),
    aboutText: z.string(),
    ctaPrimary: z.string(),
    ctaSecondary: z.string().optional(),
    metaTitle: z.string(),
    metaDescription: z.string(),
    keywords: z.array(z.string()).default([]),
  }),

  /** Page sections with component variants */
  sections: z.array(SectionDefinitionSchema),

  /** Stitch design data */
  stitch: StitchDesignSystemSchema.optional(),

  /** Target quality */
  lighthouse: z.object({
    performance: z.number().default(90),
    accessibility: z.number().default(90),
    seo: z.number().default(95),
    bestPractices: z.number().default(90),
  }).default({}),

  /** Output targets - which channels to generate for */
  targets: z.object({
    landingPage: z.boolean().default(true),
    portal: z.boolean().default(true),
    campaign: z.boolean().default(true),
  }).default({}),
});

export type DesignSpec = z.infer<typeof DesignSpecSchema>;

// ─── Design Pipeline Input ────────────────────────────────────────────────────

export const DesignPipelineInputSchema = z.object({
  /** Either clientId or prospectId */
  clientId: z.string().optional(),
  prospectId: z.string().optional(),
  /** Force template */
  templateSlug: z.string().optional(),
  /** Existing site URL to scrape */
  websiteUrl: z.string().url().optional(),
  /** Override language */
  language: z.string().optional(),
  /** Custom overrides */
  customizations: z.record(z.unknown()).optional(),
  /** Which targets to generate */
  targets: z.object({
    landingPage: z.boolean().default(true),
    portal: z.boolean().default(true),
    campaign: z.boolean().default(true),
  }).optional(),
});

export type DesignPipelineInput = z.infer<typeof DesignPipelineInputSchema>;

// ─── Design Pipeline Output ───────────────────────────────────────────────────

export const DesignPipelineOutputSchema = z.object({
  designSpec: DesignSpecSchema,
  /** Landing page HTML (for preview deploy) */
  landingPageHtml: z.string().optional(),
  /** Portal-compatible pages JSON (for editor) */
  portalPages: z.array(z.record(z.unknown())).optional(),
  /** Campaign email HTML (for outreach) */
  campaignEmailHtml: z.string().optional(),
  /** Preview URL if deployed */
  previewUrl: z.string().url().optional(),
  /** Build status */
  status: z.enum(["SUCCESS", "PARTIAL", "FAILED"]),
  warnings: z.array(z.string()).default([]),
});

export type DesignPipelineOutput = z.infer<typeof DesignPipelineOutputSchema>;
