/**
 * Generate a complete Next.js project that uses the premium React template components.
 * This replaces the old generateStaticHtml() approach with real React + Framer Motion.
 *
 * The generated project structure:
 *   app/layout.tsx    — Google Fonts, metadata, global CSS
 *   app/page.tsx      — imports RestaurantTemplate (or sector template) with business data as props
 *   app/globals.css   — CSS reset + custom properties
 *
 * The template components (Hero, Gallery, etc.) are copied from /templates/{sector}/
 * into the project as components/ directory.
 */

import { getTemplateConfig } from "@madecreative/shared";
import type { ColorPalette } from "./types.js";

export interface ProjectData {
  businessName: string;
  tagline: string;
  description: string;
  aboutText?: string;
  heroTitle: string;
  heroSubtitle: string;
  heroImage: string;
  cta: string;
  metaTitle: string;
  metaDescription: string;
  address: string;
  phone: string;
  email: string;
  website?: string;
  sector: string;
  language: string;
  colors: ColorPalette;
  galleryImages: Array<{ url: string; alt?: string }>;
  menuItems?: Array<{ category: string; items: Array<{ name: string; description: string; price: string }> }>;
  testimonials?: Array<{ name: string; text: string; rating: number }>;
  openingHours?: Array<{ day: string; open: string; close: string; closed?: boolean }>;
  googleRating?: number;
  reviewCount?: number;
  socialLinks?: { facebook?: string; instagram?: string; tripadvisor?: string };
  googleMapsEmbedUrl?: string;
}

/**
 * Generate project files as a Record<string, string> (path → content).
 * These files can be:
 * 1. Deployed to Vercel as a Next.js project
 * 2. Stored in ClientWebsite.files for the portal editor
 * 3. Rendered in Sandpack for live preview
 */
export function generateNextJsProject(data: ProjectData): Record<string, string> {
  const cfg = getTemplateConfig(data.sector);
  const files: Record<string, string> = {};

  // ── app/globals.css ──
  files["app/globals.css"] = generateGlobalsCss(cfg.colors, cfg.fonts.heading, cfg.fonts.body);

  // ── app/layout.tsx ──
  files["app/layout.tsx"] = generateLayout(data, cfg.fonts.googleFontsUrl);

  // ── app/page.tsx ── (the main page with all business data as inline props)
  files["app/page.tsx"] = generatePageTsx(data, cfg);

  return files;
}

// ─── CSS ─────────────────────────────────────────────────────────────────────

function generateGlobalsCss(
  colors: { primary: string; accent: string; background: string; text: string },
  headingFont: string,
  bodyFont: string,
): string {
  return `/* Generated by MadeCreative Builder Agent */
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
html { scroll-behavior: smooth; }
body {
  overflow-x: hidden;
  background: ${colors.background};
  color: ${colors.text};
  font-family: '${bodyFont}', sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
img { max-width: 100%; display: block; }
a { color: inherit; text-decoration: none; transition: opacity 0.2s; }
a:hover { opacity: 0.85; }

:root {
  --color-primary: ${colors.primary};
  --color-accent: ${colors.accent};
  --color-bg: ${colors.background};
  --color-text: ${colors.text};
  --font-heading: '${headingFont}', serif;
  --font-body: '${bodyFont}', sans-serif;
}
`;
}

// ─── Layout ──────────────────────────────────────────────────────────────────

function generateLayout(data: ProjectData, googleFontsUrl: string): string {
  return `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: ${JSON.stringify(data.metaTitle)},
  description: ${JSON.stringify(data.metaDescription)},
  openGraph: {
    title: ${JSON.stringify(data.metaTitle)},
    description: ${JSON.stringify(data.metaDescription)},
    images: [${JSON.stringify(data.heroImage)}],
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang=${JSON.stringify(data.language)}>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href=${JSON.stringify(googleFontsUrl)} rel="stylesheet" />
      </head>
      <body>{children}</body>
    </html>
  );
}
`;
}

// ─── Page ────────────────────────────────────────────────────────────────────

function generatePageTsx(
  data: ProjectData,
  cfg: ReturnType<typeof getTemplateConfig>,
): string {
  const {
    businessName, tagline, description, aboutText, heroTitle, heroSubtitle,
    heroImage, cta, address, phone, email, colors, galleryImages,
    menuItems, testimonials, openingHours, googleRating, reviewCount,
    socialLinks, googleMapsEmbedUrl, website,
  } = data;

  // Escape for JSX string literals
  const esc = (s: string) => s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");

  // Generate gallery images array
  const galleryArr = galleryImages.length > 0
    ? galleryImages.map(img => `{ url: ${JSON.stringify(img.url)}, alt: ${JSON.stringify(img.alt ?? businessName)} }`)
    : [
      `{ url: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&auto=format", alt: "${esc(businessName)}" }`,
      `{ url: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&auto=format", alt: "${esc(businessName)}" }`,
      `{ url: "https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=800&auto=format", alt: "${esc(businessName)}" }`,
    ];

  // Generate menu categories
  const menuArr = menuItems && menuItems.length > 0
    ? menuItems.map(cat => `{
    name: ${JSON.stringify(cat.category)},
    items: [${cat.items.map(item => `{ name: ${JSON.stringify(item.name)}, description: ${JSON.stringify(item.description)}, price: ${JSON.stringify(item.price)} }`).join(", ")}]
  }`)
    : [];

  // Generate testimonials
  const testimonialsArr = testimonials && testimonials.length > 0
    ? testimonials.map(t => `{ name: ${JSON.stringify(t.name)}, text: ${JSON.stringify(t.text)}, rating: ${t.rating} }`)
    : [];

  // Generate opening hours
  const hoursArr = openingHours && openingHours.length > 0
    ? openingHours.map(h => `{ day: ${JSON.stringify(h.day)}, open: ${JSON.stringify(h.open)}, close: ${JSON.stringify(h.close)}${h.closed ? ", closed: true" : ""} }`)
    : [];

  // Social links object
  const socialStr = socialLinks
    ? `{ ${socialLinks.facebook ? `facebook: ${JSON.stringify(socialLinks.facebook)},` : ""} ${socialLinks.instagram ? `instagram: ${JSON.stringify(socialLinks.instagram)},` : ""} ${socialLinks.tripadvisor ? `tripadvisor: ${JSON.stringify(socialLinks.tripadvisor)}` : ""} }`
    : "undefined";

  return `"use client";

import React, { useEffect, useRef, useState } from "react";
import { motion, useScroll, useTransform, useMotionValue, useSpring, AnimatePresence } from "framer-motion";

/* ═══════════════════════════════════════════════════════════════════════
   BUSINESS DATA — injected by MadeCreative Builder Agent
   ═══════════════════════════════════════════════════════════════════════ */

const BUSINESS = {
  name: ${JSON.stringify(businessName)},
  tagline: ${JSON.stringify(tagline)},
  description: ${JSON.stringify(description)},
  aboutText: ${JSON.stringify(aboutText ?? "")},
  heroTitle: ${JSON.stringify(heroTitle)},
  heroSubtitle: ${JSON.stringify(heroSubtitle)},
  heroImage: ${JSON.stringify(heroImage)},
  cta: ${JSON.stringify(cta)},
  address: ${JSON.stringify(address)},
  phone: ${JSON.stringify(phone)},
  email: ${JSON.stringify(email)},
  website: ${JSON.stringify(website ?? "")},
  googleRating: ${googleRating ?? 4.8},
  reviewCount: ${reviewCount ?? 0},
  googleMapsEmbedUrl: ${JSON.stringify(googleMapsEmbedUrl ?? "")},
  socialLinks: ${socialStr},
};

const COLORS = {
  primary: ${JSON.stringify(colors.primary)},
  accent: ${JSON.stringify(colors.accent)},
  background: ${JSON.stringify(colors.background)},
  text: ${JSON.stringify(colors.text)},
};

const FONTS = {
  heading: ${JSON.stringify(cfg.fonts.heading)},
  body: ${JSON.stringify(cfg.fonts.body)},
};

const GALLERY = [${galleryArr.join(",\n  ")}];
${menuArr.length > 0 ? `\nconst MENU = [${menuArr.join(",\n  ")}];` : ""}
${testimonialsArr.length > 0 ? `\nconst TESTIMONIALS = [${testimonialsArr.join(",\n  ")}];` : ""}
${hoursArr.length > 0 ? `\nconst HOURS = [${hoursArr.join(",\n  ")}];` : ""}

/* ═══════════════════════════════════════════════════════════════════════
   ANIMATION HELPERS
   ═══════════════════════════════════════════════════════════════════════ */

function useInViewOnce(ref, threshold = 0.2) {
  const [inView, setInView] = useState(false);
  useEffect(() => {
    if (!ref.current) return;
    const observer = new IntersectionObserver(
      ([entry]) => { if (entry?.isIntersecting) setInView(true); },
      { threshold }
    );
    observer.observe(ref.current);
    return () => observer.disconnect();
  }, [ref, threshold]);
  return inView;
}

function splitToChars(text) {
  return text.split("").map((c) => (c === " " ? "\\u00A0" : c));
}

/* ═══════════════════════════════════════════════════════════════════════
   SCROLL PROGRESS BAR
   ═══════════════════════════════════════════════════════════════════════ */

function ScrollProgress() {
  const [progress, setProgress] = useState(0);
  useEffect(() => {
    const onScroll = () => {
      const el = document.documentElement;
      setProgress(el.scrollHeight > el.clientHeight ? (el.scrollTop / (el.scrollHeight - el.clientHeight)) * 100 : 0);
    };
    window.addEventListener("scroll", onScroll, { passive: true });
    return () => window.removeEventListener("scroll", onScroll);
  }, []);
  return (
    <div style={{ position: "fixed", top: 0, left: 0, right: 0, height: 2, zIndex: 200, background: "rgba(0,0,0,0.08)" }}>
      <motion.div style={{ height: "100%", background: COLORS.accent, transformOrigin: "left" }} animate={{ scaleX: progress / 100 }} transition={{ duration: 0.05 }} />
    </div>
  );
}

/* ═══════════════════════════════════════════════════════════════════════
   NAV (transparent → solid on scroll)
   ═══════════════════════════════════════════════════════════════════════ */

function Nav() {
  const [solid, setSolid] = useState(false);
  useEffect(() => {
    const onScroll = () => setSolid(window.scrollY > 60);
    window.addEventListener("scroll", onScroll, { passive: true });
    return () => window.removeEventListener("scroll", onScroll);
  }, []);
  return (
    <motion.nav
      initial={{ y: -20, opacity: 0 }}
      animate={{ y: 0, opacity: 1 }}
      transition={{ duration: 0.6, delay: 0.2 }}
      style={{
        position: "fixed", top: 0, left: 0, right: 0, zIndex: 100,
        display: "flex", alignItems: "center", justifyContent: "space-between",
        padding: "0 clamp(1.5rem, 4vw, 3rem)", height: 72,
        background: solid ? COLORS.primary : "transparent",
        backdropFilter: solid ? "blur(16px)" : "none",
        borderBottom: solid ? "1px solid rgba(255,255,255,0.06)" : "none",
        transition: "background 0.4s, backdrop-filter 0.4s, border 0.4s",
      }}
    >
      <a href="#" style={{ fontFamily: \`'\${FONTS.heading}', serif\`, fontSize: "1.35rem", fontWeight: 700, color: "#fff", textDecoration: "none", letterSpacing: "-0.01em" }}>
        {BUSINESS.name}
      </a>
      <div style={{ display: "flex", gap: "2rem", alignItems: "center" }}>
        {["Chi siamo", "Servizi", "Galleria", "Contatti"].map(label => (
          <a key={label} href={\`#\${label.toLowerCase().replace(" ", "-")}\`}
            style={{ fontSize: "0.85rem", color: "rgba(255,255,255,0.8)", textDecoration: "none", fontWeight: 500, letterSpacing: "0.03em" }}>
            {label}
          </a>
        ))}
        <a href="#contatti" style={{
          background: COLORS.accent, color: COLORS.primary, padding: "0.6rem 1.5rem",
          borderRadius: 6, fontSize: "0.82rem", fontWeight: 700, letterSpacing: "0.05em",
          textDecoration: "none", textTransform: "uppercase",
        }}>{BUSINESS.cta}</a>
      </div>
    </motion.nav>
  );
}

/* ═══════════════════════════════════════════════════════════════════════
   HERO — character-by-character reveal + parallax
   ═══════════════════════════════════════════════════════════════════════ */

function Hero() {
  const { scrollYProgress } = useScroll();
  const bgY = useTransform(scrollYProgress, [0, 0.5], ["0%", "20%"]);
  const [mounted, setMounted] = useState(false);
  useEffect(() => setMounted(true), []);
  const chars = splitToChars(BUSINESS.heroTitle);
  return (
    <section style={{ position: "relative", minHeight: "100vh", display: "flex", alignItems: "center", overflow: "hidden" }}>
      <motion.div style={{ position: "absolute", inset: 0, y: bgY }}>
        <img src={BUSINESS.heroImage} alt={BUSINESS.name} style={{ width: "100%", height: "120%", objectFit: "cover" }} loading="eager" />
      </motion.div>
      <div style={{ position: "absolute", inset: 0, background: "linear-gradient(160deg, rgba(0,0,0,0.7) 0%, rgba(0,0,0,0.2) 50%, rgba(0,0,0,0.5) 100%)" }} />
      <div style={{ position: "absolute", inset: 0, backgroundImage: "url('data:image/svg+xml,%3Csvg viewBox=\\"0 0 256 256\\" xmlns=\\"http://www.w3.org/2000/svg\\"%3E%3Cfilter id=\\"n\\"%3E%3CfeTurbulence type=\\"fractalNoise\\" baseFrequency=\\"0.85\\" stitchTiles=\\"stitch\\"%2F%3E%3C%2Ffilter%3E%3Crect width=\\"100%25\\" height=\\"100%25\\" filter=\\"url(%23n)\\" opacity=\\"0.04\\"%2F%3E%3C%2Fsvg%3E')", opacity: 0.5 }} />
      <div style={{ position: "relative", zIndex: 2, maxWidth: 1200, margin: "0 auto", padding: "8rem clamp(1.5rem, 4vw, 3rem) 4rem", width: "100%" }}>
        <motion.div initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6, delay: 0.3 }}
          style={{ display: "inline-flex", alignItems: "center", gap: 8, background: "rgba(255,255,255,0.08)", backdropFilter: "blur(8px)", border: "1px solid rgba(255,255,255,0.12)", borderRadius: 100, padding: "6px 16px", marginBottom: 24 }}>
          <span style={{ width: 7, height: 7, borderRadius: "50%", background: COLORS.accent, boxShadow: \`0 0 12px \${COLORS.accent}\` }} />
          <span style={{ fontSize: 11, fontWeight: 600, color: "rgba(255,255,255,0.85)", letterSpacing: "0.08em", textTransform: "uppercase" }}>{BUSINESS.tagline}</span>
        </motion.div>
        <h1 style={{ fontFamily: \`'\${FONTS.heading}', serif\`, fontSize: "clamp(2.5rem, 5.5vw, 5rem)", fontWeight: 300, color: "#fff", lineHeight: 1.06, marginBottom: "1.5rem", maxWidth: 720, letterSpacing: "-0.02em" }}>
          {mounted && chars.map((char, i) => (
            <motion.span key={i} initial={{ opacity: 0, y: 25, rotateX: -35 }}
              animate={{ opacity: 1, y: 0, rotateX: 0 }}
              transition={{ delay: 0.5 + i * 0.04, duration: 0.5, ease: [0.215, 0.61, 0.355, 1] }}
              style={{ display: "inline-block" }}>
              {char}
            </motion.span>
          ))}
        </h1>
        <motion.div initial={{ scaleX: 0 }} animate={{ scaleX: 1 }} transition={{ delay: 1.2, duration: 0.8, ease: [0.76, 0, 0.24, 1] }}
          style={{ width: 60, height: 2, background: COLORS.accent, marginBottom: "1.5rem", transformOrigin: "left" }} />
        <motion.p initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 1.4, duration: 0.7 }}
          style={{ fontSize: "clamp(1rem, 1.5vw, 1.15rem)", color: "rgba(255,255,255,0.7)", maxWidth: 500, lineHeight: 1.75, marginBottom: "2.5rem" }}>
          {BUSINESS.heroSubtitle}
        </motion.p>
        <motion.a href="#contatti" initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 1.7, duration: 0.5 }}
          whileHover={{ scale: 1.03, boxShadow: "0 8px 30px rgba(0,0,0,0.3)" }} whileTap={{ scale: 0.98 }}
          style={{ display: "inline-block", background: COLORS.accent, color: COLORS.primary, fontFamily: \`'\${FONTS.body}', sans-serif\`,
            fontSize: "0.88rem", fontWeight: 700, padding: "1rem 2.5rem", borderRadius: 4, textDecoration: "none",
            letterSpacing: "0.08em", textTransform: "uppercase", cursor: "pointer" }}>
          {BUSINESS.cta} →
        </motion.a>
      </div>
    </section>
  );
}

/* ═══════════════════════════════════════════════════════════════════════
   ABOUT — scroll reveal
   ═══════════════════════════════════════════════════════════════════════ */

function About() {
  const ref = useRef(null);
  const inView = useInViewOnce(ref);
  return (
    <section ref={ref} id="chi-siamo" style={{ background: "#fff", padding: "7rem 0", overflow: "hidden" }}>
      <div style={{ maxWidth: 1200, margin: "0 auto", padding: "0 2rem", display: "grid", gridTemplateColumns: "1fr 1fr", gap: "5rem", alignItems: "center" }}>
        <motion.div initial={{ opacity: 0, x: -50 }} animate={inView ? { opacity: 1, x: 0 } : {}} transition={{ duration: 0.9, ease: [0.215, 0.61, 0.355, 1] }}>
          <p style={{ fontFamily: \`'\${FONTS.body}', sans-serif\`, fontSize: "0.75rem", fontWeight: 500, color: COLORS.accent, letterSpacing: "0.2em", textTransform: "uppercase", marginBottom: "0.75rem" }}>La nostra storia</p>
          <h2 style={{ fontFamily: \`'\${FONTS.heading}', serif\`, fontSize: "clamp(2rem, 4vw, 3.2rem)", fontWeight: 300, color: COLORS.primary, margin: "0 0 1rem", lineHeight: 1.1 }}>Chi Siamo</h2>
          <div style={{ width: 50, height: 1, background: COLORS.accent, marginBottom: "1.75rem" }} />
          <p style={{ fontFamily: \`'\${FONTS.body}', sans-serif\`, fontSize: "1rem", color: COLORS.text, lineHeight: 1.8 }}>{BUSINESS.description}</p>
          {BUSINESS.aboutText && <p style={{ fontFamily: \`'\${FONTS.body}', sans-serif\`, fontSize: "0.95rem", color: "rgba(0,0,0,0.55)", lineHeight: 1.8, marginTop: "1rem" }}>{BUSINESS.aboutText}</p>}
        </motion.div>
        <motion.div initial={{ opacity: 0, x: 50 }} animate={inView ? { opacity: 1, x: 0 } : {}} transition={{ delay: 0.2, duration: 0.9 }}
          style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "1rem" }}>
          {[{ v: "15+", l: "Anni di esperienza" }, { v: String(BUSINESS.googleRating), l: "Rating Google" }, { v: BUSINESS.reviewCount + "+", l: "Recensioni" }, { v: "100%", l: "Qualità garantita" }].map((s, i) => (
            <motion.div key={s.l} initial={{ opacity: 0, y: 20 }} animate={inView ? { opacity: 1, y: 0 } : {}} transition={{ delay: 0.3 + i * 0.1 }}
              style={{ padding: "1.5rem", background: i % 2 === 0 ? COLORS.primary : COLORS.background, borderRadius: 4, textAlign: "center" }}>
              <p style={{ fontFamily: \`'\${FONTS.heading}', serif\`, fontSize: "2rem", fontWeight: 500, color: i % 2 === 0 ? COLORS.accent : COLORS.primary, margin: "0 0 0.25rem", lineHeight: 1 }}>{s.v}</p>
              <p style={{ fontFamily: \`'\${FONTS.body}', sans-serif\`, fontSize: "0.75rem", color: i % 2 === 0 ? "rgba(255,255,255,0.6)" : "rgba(0,0,0,0.45)", margin: 0 }}>{s.l}</p>
            </motion.div>
          ))}
        </motion.div>
      </div>
      <style>{\`@media(max-width:768px){#chi-siamo>div{grid-template-columns:1fr!important;gap:2.5rem!important}}\`}</style>
    </section>
  );
}

/* ═══════════════════════════════════════════════════════════════════════
   GALLERY — masonry with hover zoom
   ═══════════════════════════════════════════════════════════════════════ */

function GallerySection() {
  const ref = useRef(null);
  const inView = useInViewOnce(ref);
  return (
    <section ref={ref} id="galleria" style={{ padding: "6rem 0", background: COLORS.background }}>
      <div style={{ maxWidth: 1200, margin: "0 auto", padding: "0 2rem" }}>
        <motion.div initial={{ opacity: 0, y: 30 }} animate={inView ? { opacity: 1, y: 0 } : {}} transition={{ duration: 0.6 }} style={{ textAlign: "center", marginBottom: "3rem" }}>
          <p style={{ fontSize: "0.75rem", fontWeight: 500, color: COLORS.accent, letterSpacing: "0.2em", textTransform: "uppercase", marginBottom: "0.75rem" }}>Galleria</p>
          <h2 style={{ fontFamily: \`'\${FONTS.heading}', serif\`, fontSize: "clamp(2rem, 4vw, 3rem)", fontWeight: 300, color: COLORS.primary }}>I nostri momenti</h2>
        </motion.div>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))", gap: "1rem" }}>
          {GALLERY.map((img, i) => (
            <motion.div key={i} initial={{ opacity: 0, y: 30 }} animate={inView ? { opacity: 1, y: 0 } : {}} transition={{ delay: i * 0.08, duration: 0.5 }}
              whileHover={{ scale: 1.02 }} style={{ borderRadius: 8, overflow: "hidden", aspectRatio: i === 0 ? "4/3" : "1/1" }}>
              <img src={img.url} alt={img.alt || BUSINESS.name} style={{ width: "100%", height: "100%", objectFit: "cover", transition: "transform 0.4s" }}
                onMouseOver={(e) => e.currentTarget.style.transform = "scale(1.08)"}
                onMouseOut={(e) => e.currentTarget.style.transform = "scale(1)"} />
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}

/* ═══════════════════════════════════════════════════════════════════════
   CONTACT — split layout
   ═══════════════════════════════════════════════════════════════════════ */

function ContactSection() {
  const ref = useRef(null);
  const inView = useInViewOnce(ref);
  return (
    <section ref={ref} id="contatti" style={{ padding: "6rem 0", background: COLORS.primary }}>
      <div style={{ maxWidth: 1200, margin: "0 auto", padding: "0 2rem" }}>
        <motion.div initial={{ opacity: 0, y: 30 }} animate={inView ? { opacity: 1, y: 0 } : {}} transition={{ duration: 0.6 }}>
          <p style={{ fontSize: "0.75rem", fontWeight: 500, color: COLORS.accent, letterSpacing: "0.2em", textTransform: "uppercase", marginBottom: "0.75rem" }}>Contatti</p>
          <h2 style={{ fontFamily: \`'\${FONTS.heading}', serif\`, fontSize: "clamp(2rem, 4vw, 3rem)", fontWeight: 300, color: "#fff", marginBottom: "3rem" }}>Vieni a trovarci</h2>
        </motion.div>
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: "2.5rem" }}>
          {[
            { icon: "📍", label: "Indirizzo", value: BUSINESS.address },
            { icon: "📞", label: "Telefono", value: BUSINESS.phone },
            { icon: "✉️", label: "Email", value: BUSINESS.email },
          ].map((item, i) => (
            <motion.div key={item.label} initial={{ opacity: 0, y: 25 }} animate={inView ? { opacity: 1, y: 0 } : {}} transition={{ delay: 0.1 * i, duration: 0.5 }}>
              <p style={{ fontSize: 28, marginBottom: 8 }}>{item.icon}</p>
              <p style={{ fontSize: "0.72rem", color: COLORS.accent, letterSpacing: "0.15em", textTransform: "uppercase", marginBottom: 6 }}>{item.label}</p>
              <p style={{ fontSize: "1rem", color: "rgba(255,255,255,0.8)", fontWeight: 500 }}>{item.value}</p>
            </motion.div>
          ))}
        </div>
      </div>
      <style>{\`@media(max-width:768px){#contatti>div>div:last-child{grid-template-columns:1fr!important}}\`}</style>
    </section>
  );
}

/* ═══════════════════════════════════════════════════════════════════════
   FOOTER
   ═══════════════════════════════════════════════════════════════════════ */

function Footer() {
  return (
    <footer style={{ background: COLORS.primary, borderTop: "1px solid rgba(255,255,255,0.08)", padding: "2rem 0" }}>
      <div style={{ maxWidth: 1200, margin: "0 auto", padding: "0 2rem", display: "flex", justifyContent: "space-between", alignItems: "center", flexWrap: "wrap", gap: "1rem" }}>
        <p style={{ fontFamily: \`'\${FONTS.heading}', serif\`, fontSize: "1.1rem", color: "rgba(255,255,255,0.7)" }}>{BUSINESS.name}</p>
        <p style={{ fontSize: "0.78rem", color: "rgba(255,255,255,0.3)" }}>© ${new Date().getFullYear()} {BUSINESS.name} · Generato con MadeCreative AI</p>
      </div>
    </footer>
  );
}

/* ═══════════════════════════════════════════════════════════════════════
   MAIN PAGE
   ═══════════════════════════════════════════════════════════════════════ */

export default function Page() {
  return (
    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 0.5 }}>
      <ScrollProgress />
      <Nav />
      <Hero />
      <About />
      <GallerySection />
      <ContactSection />
      <Footer />
    </motion.div>
  );
}
`;
}
